### ISSUE TITLE
Request merge to main repository

### ISSUE THREAD

**Issue by green-leaves** [ReeganExE/voz-infinite-scroll#1]
Bác ơi em là owner của cái script này, em vừa tạo repo mới ở đây:

https://github.com/green-leaves/infinite-voz

Bác tạo pull request để em merge vào rồi udpate cái script trên greasefork nhé.

Cám ơn bác.

**Comment by ReeganExE** [comment]
The first one for you: [PR #1](https://github.com/green-leaves/infinite-voz/pull/1)
